# Generated by Django 3.1.4 on 2021-12-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20211210_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Status',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
    ]
