# Generated by Django 3.1.4 on 2021-12-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Pacient',
            new_name='Patient',
        ),
    ]
