export const users = [
  {
    id: 1,
    name: "Admin",
    surname: "",
    email: "admin@clinic.com",
    password: "1234",
    type: "admin",
  },
  {
    id: 2,
    name: "Peter",
    surname: "Parker",
    dni: "41121321",
    phone: "1293412",
    gender: "male",
    age: "1956-03-12",
    medical_plan: "pami",
    social_work: "",
    email: "peterparker@clinic.com",
    password: "1234",
    type: "pacient",
  },
  {
    id: 3,
    name: "Harry",
    surname: "Potter",
    email: "harry@clinic.com",
    password: "1234",
    type: "doctor",
    active: 0,
    specialty: "General",
  },
  {
    id: 4,
    name: "Mary",
    surname: "Jane",
    email: "mary@clinic.com",
    password: "1234",
    type: "doctor",
    active: 1,
    specialty: "Traumatologist",
  },
  {
    id: 5,
    name: "John",
    surname: "Cena",
    email: "mary@clinic.com",
    password: "1234",
    type: "doctor",
    active: 1,
    specialty: "Dentist",
  },
  {
    id: 6,
    name: "Harry",
    surname: "Osborn",
    email: "mary@clinic.com",
    password: "1234",
    type: "doctor",
    active: 1,
    specialty: "Oftalmologist",
  },
  {
    id: 7,
    name: "Chakie",
    surname: "Chan",
    email: "mary@clinic.com",
    password: "1234",
    type: "doctor",
    active: 1,
    specialty: "General",
  },
  {
    id: 8,
    name: "Jet",
    surname: "Lee",
    email: "mary@clinic.com",
    password: "1234",
    type: "doctor",
    active: 1,
    specialty: "Oftalmologist",
  },
]

export const turns = [
  {
    id: 1,
    date: "22/12/2021",
    time: "14:30:00",
    doctor: 8,
    active: 1,
  },
  {
    id: 2,
    date: "22/12/2021",
    time: "15:00:00",
    doctor: 8,
    active: 1,
  },
  {
    id: 3,
    date: "22/12/2021",
    time: "15:30:00",
    doctor: 8,
    active: 1,
  },
  {
    id: 4,
    date: "22/12/2021",
    time: "16:00:00",
    doctor: 8,
    active: 0,
  },
  {
    id: 5,
    date: "22/12/2021",
    time: "14:30:00",
    doctor: 7,
    active: 1,
  },
  {
    id: 6,
    date: "22/12/2021",
    time: "15:00:00",
    doctor: 7,
    active: 1,
  },
  {
    id: 7,
    date: "22/12/2021",
    time: "15:30:00",
    doctor: 7,
    active: 1,
  },
]
