export const users = [
  {
    name: "Admin",
    surname: "",
    email: "admin@clinic.com",
    password: "1234",
    type: "admin",
  },
  {
    name: "Peter",
    surname: "Parker",
    identy: "41121321",
    phone: "1293412",
    gender: "male",
    age: "12-03-1956",
    medical_plan: "pami",
    social_work: "",
    email: "peterparker@clinic.com",
    password: "1234",
    type: "pacient",
  },
  {
    name: "Harry",
    surname: "Potter",
    email: "harry@clinic.com",
    password: "1234",
    type: "doctor",
    active: 0,
    specialty: "General",
  },
  {
    name: "Mary",
    surname: "Jane",
    email: "mary@clinic.com",
    password: "1234",
    type: "doctor",
    active: 1,
    specialty: "Traumatologist",
  },
  {
    name: "John",
    surname: "Cena",
    email: "mary@clinic.com",
    password: "1234",
    type: "doctor",
    active: 1,
    specialty: "Dentist",
  },
  {
    name: "Harry",
    surname: "Osborn",
    email: "mary@clinic.com",
    password: "1234",
    type: "doctor",
    active: 1,
    specialty: "Oftalmologist",
  },
  {
    name: "Chakie",
    surname: "Chan",
    email: "mary@clinic.com",
    password: "1234",
    type: "doctor",
    active: 1,
    specialty: "General",
  },
  {
    name: "Jet",
    surname: "Lee",
    email: "mary@clinic.com",
    password: "1234",
    type: "doctor",
    active: 1,
    specialty: "Oftalmologist",
  },
]
