# Generated by Django 3.1.4 on 2021-12-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20211212_0804'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacient',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='extenduser',
            old_name='is_pacient',
            new_name='is_patient',
        ),
    ]
