# Generated by Django 3.1.4 on 2021-12-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211212_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='is_patient',
            field=models.BooleanField(default=False, verbose_name='patient status'),
        ),
    ]
